pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'echo "building docker"'
            }
        }
        stage('test') {
            steps {
                sh 'echo "testing docker"'
            }
        }
        stage('deploy') {
            steps {
                sh 'echo "deploying"'
            }
        }
    }
}
